//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMPAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ImagePath { get; set; }
        public string VideoPath { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public string Status { get; set; }
        public Nullable<int> AddedById { get; set; }
        public string Type { get; set; }
        public string Trending { get; set; }
        public bool IsActive { get; set; }
    }
}
